GRANT SELECT, INSERT, UPDATE ON TABLE APP.APP_USER TO VHUB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE APP.EVENT TO VHUB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE APP.ACTIVITY TO VHUB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE APP.VOLUNTEER TO VHUB_USER;